### PR TITLE
Add some basic testing using some test files and a golden text representation of tokens

### PR DESCRIPTION
**Pull request by DanTup**
@bkonyi @devoncarew it's been bugging me that we had no good way to syntax changes besides reviewing the results manually. Dart-Code has [an open PR](https://github.com/Dart-Code/Dart-Code/pull/4067) (that will need to be redirect here when ready) that refactors quite a lot of this code that re-reminded me about this.

I found https://github.com/PanAeon/vscode-tmgrammar-test and added some basic tests to the Dart-Code repo, but really there should be tests here too. @bkonyi pointed out DevTools has some grammar parsing so rather than setting up TypeScript/npm here, it seems like we might be able to replicate that without much effort.

This PR is not complete (it has span_parser lifted from DevTools with some slight tweaks, and I think it's failing to parse some of my test code) but I wanted to get some feedback on the idea before going too far.

- `test/golden_test.dart` is the test code
- `test/support/span_parser.dart` is the grammar parser lifted from DevTools (which we may want to aim to share)
- `test/test_files/*.dart` are files we use for testing
- `test/test_file/*.dart.golden` are text files showing the scopes for each token

The output format currently matches https://github.com/PanAeon/vscode-tmgrammar-test which gives us something to compare against to ensure everything is parsing correctly (which it's not yet, but I haven't dug into because I didn't want to go too far without some feedback).

WDYT?

### CODE REVIEW

**Comment by pouyakary** [comment]
@DanTup this seems really nice. I remember using something like this in the V language's vscode grammar. I'll try to add as many tests as I can in the coming days into the PR.

**Comment by devoncarew** [comment]
@DanTup - this looks great!

In terms of shared impl between devtools and this repo, if there are only two uses, it may be worth some effort to avoid having to publish a new package. Some ideas I can think of are:

- copying the classes, adding docs that they're copied, and manually (occasionally) syncing them
- referencing the devtools package from here via a pubspec git dep?
- cloning the devtools repo here during the CI, and copying the necessary libraries?

**Comment by DanTup** [comment]
I guess since the textmate grammar spec isn't changing, the class will probably be pretty static once it's working as planned. I'll work through the few failures I see running it here (and also look for any differences with the npm tool noted above) and contribute any changes back to DevTools, and then copy it here and finish up this PR to add some testing. Thanks!

**Comment by DanTup** [comment]
@devoncarew the parser now handles the latest changes in this grammar, so this is ready for review. I've added a bunch of test files and generated goldens for them using the Dart parser from DevTools.

Separately, I generated the same files using an npm tool and performed some minor cleanup to produce the same output ([code here](https://gist.github.com/DanTup/66b3e91db09385dc3f9baf224d184c59)) and the output matches (meaning our parser should produce the same results as VS Code users would see).

For future contributions, I suggest people should add code to `test/test_files` that cover the changes being made and re-generate the goldens, in a separate commit to the rest of the PR, so that it's easier to see the exact changes being made (rather than just new test code and no visibility of what the pre-change grammar produces for that code). I can add some notes to a `CONTRIBURING` file, although I note there isn't one currently - I'm not sure if there's a standard template to use (the ones in Dart/Flutter projects talk about CLAs, although they're not the same).

**Comment by devoncarew** [comment]
> This looks great! Are these tests being exercised on the CI? I don't see us running dart tests in the github action config here. We should probably hook this up to the CI before landing.

If you do plan to land something like this, and would like to instead do it as a follow-up PR, let me know.

**Comment by DanTup** [comment]
> Are these tests being exercised on the CI?

Oh, good call. I'll sort this out (and contributing notes) this week. Makes no difference to me whether it's same or another PR, so whatever makes it easier for you. I'll add to this one if unmerged when I get to it, and if merged I'll open a new one.

Thanks!

**Comment by DanTup** [comment]
@devoncarew I've added some contribution notes + enabled on bots, please take a look (test results show in the bot run at https://github.com/dart-lang/dart-syntax-highlight/runs/8229532148?check_suite_focus=true#step:8:1).

**Review by devoncarew — APPROVED** [review]

**Pull request merged**
